const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const AUTH_PROVIDER_GOOGLE = "GOOGLE";
const AUTH_PROVIDER_FB = "FACEBOOK";
const AUTH_ROLE_USER = "USER";
const AUTH_ROLE_GUEST = "GUEST";

export default {
    LOGIN,
    LOGOUT,
    AUTH_PROVIDER_GOOGLE,
    AUTH_PROVIDER_FB,
    AUTH_ROLE_USER,
    AUTH_ROLE_GUEST
};